coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%
    patch:
      default:
        target: 60%

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false

ignore:
  - "test/**/*"
  - "**/dist/**"
